// Shared Data Layer
const categories = [
    { id: 'repairs', name: 'Repairs', type: 'image', visual: 'repairs_bg_localized_1774610544054.png', gradient: 'linear-gradient(135deg, #254B96 0%, #1a3270 100%)', description: 'Services focused on fixing damaged or faulty items to restore them to proper working condition.' },
    { id: 'maintenance', name: 'Maintenance', type: 'image', visual: 'maintenance_bg_localized_1774610594834.png', gradient: 'linear-gradient(135deg, #006F3C 0%, #004d2a 100%)', description: 'Routine services to keep your spaces, equipment, and systems in good condition and prevent breakdowns.' },
    { id: 'electrical', name: 'Electrical Services', type: 'image', visual: 'electrical_bg_localized_1774610700416.png', gradient: 'linear-gradient(135deg, #DE902D 0%, #B45309 100%)', description: 'Solutions related to the installation, repair, and management of electrical systems and power-related needs.' },
    { id: 'lifestyle', name: 'Lifestyle', type: 'image', visual: 'lifestyle.png', gradient: 'linear-gradient(135deg, #27B376 0%, #006F3C 100%)', description: 'Convenience services that support daily living and make everyday tasks easier and more manageable.' },
    { id: 'building', name: 'Building', type: 'emoji', visual: '🏗️', gradient: 'linear-gradient(135deg, #254B96 0%, #173366 100%)', description: 'Services involved in the construction, renovation, and improvement of physical spaces and structures.' },
    { id: 'personal', name: 'Personal Care', type: 'image', visual: 'cat-personal.png', gradient: 'linear-gradient(135deg, #DE902D 0%, #B45309 100%)', description: 'Services centered on individual grooming, hygiene, and overall personal well-being.' },
    { id: 'logistics', name: 'Logistics & Moving', type: 'image', visual: 'logistics.png', gradient: 'linear-gradient(135deg, #27B376 0%, #006F3C 100%)', description: 'Services that handle the movement, delivery, and transportation of people, goods, or items from one place to another.' },
    { id: 'others', name: 'Others', type: 'emoji', visual: '✨', gradient: 'linear-gradient(135deg, #BF212F 0%, #a01b27 100%)', description: 'Custom or specialized services designed to meet unique, urgent, or less common needs.' }
];

let allServicesData = [
    { id: 1, catId: 'maintenance', name: 'Cleaning', location: 'Ifite', description: 'Thorough home, office, and post-construction cleaning services to keep your space spotless and comfortable.', icon: 'fa-broom', price: 4500 },
    { id: 2, catId: 'repairs', name: 'Expert Plumbing', location: 'Regina', description: 'Fixing leaks, pipe installations, drainage issues, and everything in between to keep your water systems running smoothly.', icon: 'fa-faucet', price: 8000 },
    { id: 3, catId: 'repairs', name: 'Welding', location: 'Amansea', description: 'Professional metal joining, fabrication, and structural repairs for both residential and commercial needs.', icon: 'fa-tools', price: 0 },
    { id: 4, catId: 'maintenance', name: 'Decluttering', location: 'Arroma', description: 'Organized removal and sorting of unwanted items to restore order and breathing room to your space.', icon: 'fa-box-open', price: 0 },
    { id: 5, catId: 'maintenance', name: 'Fumigation', location: 'Tempsite', description: 'Effective pest control and fumigation treatments to protect your home or business from infestation.', icon: 'fa-spray-can', price: 0 },
    { id: 6, catId: 'electrical', name: 'Wiring', location: 'Okpuno', description: 'Safe and compliant electrical wiring installations and repairs for new builds and existing structures.', icon: 'fa-plug', price: 8000 },
    { id: 7, catId: 'electrical', name: 'Fixtures', location: 'Amaenyi', description: 'Professional fitting of lighting, switches, sockets, and other electrical fixtures.', icon: 'fa-lightbulb', price: 0 },
    { id: 8, catId: 'electrical', name: 'Appliance installation and maintenance', location: 'Amawbia', description: 'Expert setup and routine servicing of household and commercial appliances to extend their lifespan.', icon: 'fa-tv', price: 0 },
    { id: 9, catId: 'lifestyle', name: 'Shopping', location: 'Government house', description: 'Personal shopping for essentials and other needs, delivered to your preferred location.', icon: 'fa-shopping-cart', price: 0 },
    { id: 10, catId: 'lifestyle', name: 'Home car-washing', location: 'Aguawka', description: 'Convenient, thorough vehicle cleaning carried out right at your doorstep.', icon: 'fa-car', price: 0 },
    { id: 11, catId: 'building', name: 'Carpentry', location: 'Ngozika', description: 'Custom woodwork, furniture making, repairs, and installations crafted to your specification.', icon: 'fa-hammer', price: 7000 },
    { id: 12, catId: 'building', name: 'Painting', location: 'Udoka', description: 'Interior and exterior painting services that give your space a beautiful, refreshed finish.', icon: 'fa-paint-roller', price: 10000 },
    { id: 13, catId: 'personal', name: 'Hairstyling/Barbing', location: 'Kwata', description: 'Professional hair and grooming services brought directly to your home or preferred location.', icon: 'fa-cut', price: 4000 },
    { id: 14, catId: 'personal', name: 'Laundry', location: 'Ifite', description: 'Washing, drying, ironing, and folding services handled with care and returned fresh.', icon: 'fa-tshirt', price: 3000 },
    { id: 15, catId: 'logistics', name: 'Relocation', location: 'Regina', description: 'Stress-free residential and commercial moving services, carefully handled from start to finish.', icon: 'fa-truck-loading', price: 15000 },
    { id: 16, catId: 'logistics', name: 'Haulage', location: 'Amansea', description: 'Reliable transportation of large equipment, furniture, and bulk goods to any destination.', icon: 'fa-truck-moving', price: 0 },
    { id: 17, catId: 'logistics', name: 'Errands', location: 'Arroma', description: 'Trusted assistance with time-sensitive tasks and day-to-day runs so you can focus on what matters.', icon: 'fa-running', price: 2000 },
    { id: 18, catId: 'others', name: 'Personalized, tailored, or emergency services', location: 'Tempsite', description: 'Can’t find what you need? We accommodate unique, custom, and urgent requests to ensure no need goes unmet.', icon: 'fa-star', price: 7500 }
];

let providersData = [
    { id: 104, serviceId: 1, name: 'Ojimba Munachi Precious', location: 'Ifite', price: 3000, rating: 5.0, photo: 'images/providers/image29.jpg', about: 'Professional Cleaning, laundry, cooking and errand services.', portfolio: ['images/providers/image29.jpg', 'images/providers/image36.jpg'], jobs: 0 },
    { id: 105, serviceId: 14, name: 'Okeke Ebuka Paul', location: 'Ziks Avenue', price: 500, rating: 5.0, photo: 'images/providers/image10.jpg', about: 'Laundry Services', portfolio: ['images/providers/image10.jpg', 'images/providers/image25.jpg'], jobs: 0 },
    { id: 106, serviceId: 1, name: 'Jennifer Amarachi Ajuk (Haven Shine Cleaning)', location: 'Amawbia', price: 20000, rating: 5.0, photo: 'provider-sarah.png', about: 'Professional cleaning service specializing in deep cleaning, upholstery, post construction and maintenance cleaning.', jobs: 0 },
    { id: 107, serviceId: 13, name: 'Patrick Chisom Blessing (Sommy_hair)', location: 'Ifite', price: 5000, rating: 5.0, photo: 'images/providers/image22.jpg', about: 'Professional hairstylist specializing in styling for all kinds hair types like braiding, Ghana Weaving, inner weaving, crochets, Gel styling, fixing of weave-ons.', portfolio: ['images/providers/image22.jpg', 'images/providers/image24.jpg', 'images/providers/image23.jpg'], jobs: 0 },
    { id: 108, serviceId: 13, name: 'Godsfavour Ibekwe (Mma_Signature)', location: 'Ifite', price: 5000, rating: 5.0, photo: 'images/providers/image35.jpg', about: 'Professional hairstyling and grooming.', portfolio: ['images/providers/image35.jpg', 'images/providers/image3.jpg', 'images/providers/image26.jpg', 'images/providers/image4.jpg'], jobs: 0 },
    { id: 109, serviceId: 12, name: 'Ude Michael Ukpai (Doclux Paints)', location: 'Enugu', price: 400000, rating: 5.0, photo: 'images/providers/image1.jpg', about: 'Paint sales and professional painting services. Price Range: ₦400,000 - ₦3,500,000.', portfolio: ['images/providers/image1.jpg', 'images/providers/image8.jpg', 'images/providers/image7.jpg', 'images/providers/image15.jpg'], jobs: 0 },
    { id: 110, serviceId: 18, name: 'Winner Arema (Alpha Tech)', location: 'Item 7, Awka', price: 100000, rating: 5.0, photo: 'images/providers/image6.jpg', about: 'Interior decoration, furniture and electrical services.', portfolio: ['images/providers/image6.jpg', 'images/providers/image9.jpg', 'images/providers/image19.jpg'], jobs: 0 },
    { id: 111, serviceId: 2, name: 'Mbah ThankGod Arinze (J-vic)', location: 'PH', price: 25000, rating: 5.0, photo: 'images/providers/image5.jpg', about: 'Expert plumbing services and repairs.', portfolio: ['images/providers/image5.jpg', 'images/providers/image2.jpg', 'images/providers/image41.jpg', 'images/providers/image13.jpg'], jobs: 0 },
    { id: 112, serviceId: 12, name: 'Chinedu Samuel Nweke (Edu Painting)', location: 'Awka', price: 500000, rating: 5.0, photo: 'images/providers/image11.jpg', about: 'Professional screeding, painting, and cleaning services for residential and commercial properties. Price Range: ₦500,000 - ₦3,000,000.', portfolio: ['images/providers/image11.jpg', 'images/providers/image28.jpg', 'images/providers/image12.jpg'], jobs: 0 },
    { id: 113, serviceId: 2, name: 'Edeh Nicodemus Ejiofor (Prosper Plumbing)', location: 'Awka', price: 50000, rating: 5.0, photo: 'images/providers/image50.jpg', about: 'Plumbing and building toilet installations. Price Range: ₦50,000 - ₦600,000.', portfolio: ['images/providers/image50.jpg', 'images/providers/image47.jpg', 'images/providers/image49.jpg', 'images/providers/image46.jpg'], jobs: 0 },
    { id: 114, serviceId: 17, name: 'Obum Chisom Samuel (Chim-som Logistics)', location: 'Awka', price: 2000, rating: 5.0, photo: 'provider-sarah.png', about: 'Efficient errands and logistics services.', jobs: 0 },
    { id: 115, serviceId: 1, name: 'Umeadi Mary Chiemelie (Thrillers Cleaning)', location: 'Amaenyi', price: 25000, rating: 5.0, photo: 'provider-sarah.png', about: 'House cleaning, deep cleaning, post construction cleaning, and offices and homes cleaning.', jobs: 0 },
    { id: 116, serviceId: 2, name: 'Uzoechie Chizoba Hillary', location: 'Ifite', price: 50000, rating: 5.0, photo: 'images/providers/image14.jpg', about: 'Professional plumbing work. Price Range: ₦50,000 - ₦2,000,000.', portfolio: ['images/providers/image14.jpg', 'images/providers/image18.jpg', 'images/providers/image16.jpg'], jobs: 0 },
    { id: 117, serviceId: 14, name: 'Omeni Victor (Diamond Laundry)', location: 'Ifite', price: 1000, rating: 5.0, photo: 'provider-sarah.png', about: 'Quality dry cleaning and laundry services.', jobs: 0 },
    { id: 118, serviceId: 11, name: 'Chiemerie Ozokolo (MP Carpenter)', location: 'Ifite', price: 60000, rating: 5.0, photo: 'images/providers/image20.jpg', about: 'Expert Furniture Craft & Interior. Price Range: ₦60,000 - ₦350,000.', portfolio: ['images/providers/image20.jpg', 'images/providers/image21.jpg', 'images/providers/image17.jpg'], jobs: 0 },
    { id: 119, serviceId: 6, name: 'Chibueze Nwoka (Kingz Engineering)', location: 'Awka', price: 8000, rating: 5.0, photo: 'images/providers/image44.jpg', about: 'Electrical, Solar and Smart home tech', portfolio: ['images/providers/image44.jpg', 'images/providers/image32.jpg', 'images/providers/image45.jpg', 'images/providers/image48.jpg'], jobs: 0 },
    { id: 120, serviceId: 12, name: 'Amaifeobu Miracle C. (Albagreat Consortium)', location: 'Obosi', price: 700000, rating: 5.0, photo: 'images/providers/image38.jpg', about: 'Paint production, Painting, House Cleaning. Price Range: ₦700,000 - ₦3,000,000.', portfolio: ['images/providers/image38.jpg', 'images/providers/image30.jpg', 'images/providers/image51.jpg'], jobs: 0 },
    { id: 121, serviceId: 11, name: 'Obot Daniel Sylvester (Dnl_furnitures)', location: 'Ifite', price: 150000, rating: 5.0, photo: 'images/providers/image33.jpg', about: 'Interior design', portfolio: ['images/providers/image33.jpg', 'images/providers/image27.jpg', 'images/providers/image31.jpg', 'images/providers/image34.jpg'], jobs: 0 },
    { id: 122, serviceId: 1, name: 'Ezezike Hope Chinonso (Hopeceecleaningservices)', location: 'Awka', price: 4500, rating: 5.0, photo: 'provider-sarah.png', about: 'Cleaning Services and errand runs.', jobs: 0 },
    { id: 123, serviceId: 1, name: 'Jessyca Udeogu (Ssyca Cleaning Services)', location: 'Udoka', price: 25000, rating: 5.0, photo: 'images/providers/image42.jpg', about: 'Cleaning services. Price Range: ₦25,000 - ₦80,000.', portfolio: ['images/providers/image42.jpg', 'images/providers/image37.jpg', 'images/providers/image43.jpg', 'images/providers/image39.jpg'], jobs: 0 },
    { id: 124, serviceId: 13, name: 'Emelobe Ijeoma Shalom (Hair by Shalom)', location: 'Ifite', price: 10000, rating: 5.0, photo: 'images/providers/image40.jpg', about: 'Braiding, weaving, lashes and locs. Price Range: ₦10,000 - ₦20,000.', portfolio: ['images/providers/image40.jpg'], jobs: 0 },
    { id: 125, serviceId: 1, name: 'Chinyere Okeke (3CCLEANING & Errand Services)', location: 'Asaba', price: 6000, rating: 5.0, photo: 'provider-sarah.png', about: 'Household cleaning, maintenance, and post construction cleaning services.', jobs: 0 },
    { id: 126, serviceId: 15, name: 'Chidinma Ofili (Purity Agency)', location: 'Ifite', price: 15000, rating: 5.0, photo: 'provider-sarah.png', about: 'Professional relocation and cleaning services.', jobs: 0 },
    { id: 127, serviceId: 13, name: 'Lawrence Oluebube Divine (She\'s Divine Beauty Salon)', location: 'Yahoo Junction, Ifite', price: 4000, rating: 5.0, photo: 'provider-sarah.png', about: 'Professional braiding and hair styling services.', jobs: 0 }
];
const faqData = [
    {
        category: 'How it Works',
        questions: [
            { q: 'What is Serva?', a: 'Serva is an online service marketplace that connects you with trusted, verified local service providers in Awka, Anambra State. Whether you need a plumber, cleaner, electrician, or handyman, Serva lets you find, compare, and book the service you need quickly and conveniently from your phone or computer.' },
            { q: 'What kinds of services can I book on Serva?', a: 'You can book a wide range of everyday, traditional services including plumbing, electrical repairs, cleaning, maintenance and handyman work, errands, and more. We are constantly onboarding new providers, so the list keeps growing. Browse our services page to see everything currently available near you.' },
            { q: 'How do I book a service?', a: 'Booking is simple. Browse or search for the service you need, view available providers in your area, select your preferred provider, choose your date and time, and confirm your booking. You will receive an instant confirmation and be kept updated throughout the process.' },
            { q: 'How quickly can I get a service provider after booking?', a: 'This depends on the type of service and the service provider’s availability. For many services, same-day or next-day availability is possible. Once your booking is confirmed, you will be given an estimated arrival time and receive updates as the provider makes their way to you.' },
            { q: 'Can I schedule a service in advance or is it same-day only?', a: 'Both options are available. You can book a service for immediate or same-day delivery (depending on the type of service and the service provider’s availability), or schedule it for a future date and time that suits you. We recommend booking in advance for better time slot options.' },
            { q: 'Can I choose my preferred service provider, or is one assigned to me?', a: 'You are in control. Serva allows you to browse provider profiles, read their reviews and ratings, and choose who you want to work with.' },
            { q: 'How do I track my service after booking?', a: 'Once your booking is confirmed and underway, you will receive real-time tracking updates so you always know the status of your service. From confirmation to arrival to completion, Serva keeps you informed every step of the way.' }
        ]
    },
    {
        category: 'Payment',
        questions: [
            { q: 'How much does it cost to use Serva as a customer?', a: 'There are no platform fees, subscription costs, or hidden charges added to your bill, you only pay the agreed service charge.' },
            { q: 'When exactly do I pay (before or after the service)?', a: 'The entire payment is made upfront. However, service providers receive only the cost of materials or preparation upfront (where applicable), and they receive the full payment/service fee once the service has been delivered to your satisfaction. This protects both the customer and service provider; and also ensures accountability from the provider.' },
            { q: 'How do I make payment?', a: 'Payment details and accepted methods are clearly communicated at checkout.' },
            { q: 'Are there any hidden charges or extra fees?', a: 'None at all. Serva operates a zero hidden charges policy. The price you see is the price you pay. Any applicable service fees or charges are communicated clearly and upfront before you confirm your booking, no surprises.' },
            { q: 'What if I am not satisfied, can I get a refund?', a: 'Your satisfaction matters to us. If a service does not meet the agreed standard or expectation, please raise a complaint through the platform immediately after service delivery. Our team will review the case and work to resolve it fairly, which may include a compensation depending on the circumstances.' },
            { q: 'What happens if I pay and the provider does not show up?', a: 'In the event of a no-show, please contact our support team immediately and we will assist you in rebooking or resolving the issue promptly.' }
        ]
    },
    {
        category: 'Trust & Safety',
        questions: [
            { q: 'How do I know the service providers are trustworthy?', a: 'Every service provider on Serva goes through a strict vetting and onboarding process before they are listed on the platform. We verify their identity, assess their skill level, and ensure they understand and agree to Serva\'s standards of service delivery, professionalism, and customer rights.' },
            { q: 'What documents are required from providers?', a: 'Service providers are required to submit a valid National Identification Number (NIN) and a CAC registration number for registered businesses. Additional documentation may be required depending on the nature of the service. This ensures every provider on Serva is identifiable and accountable.' },
            { q: 'Can I read reviews before booking a provider?', a: 'Yes. Every provider on Serva has a profile that includes ratings and reviews from previous customers. We encourage all customers to leave honest feedback after each service. This helps the community make informed decisions and motivates providers to maintain high standards.' },
            { q: 'What if a provider damages my property during service delivery?', a: 'In the event of property damage caused by a provider, please document the damage immediately and report it to Serva\'s support team through the platform. We take such incidents seriously and will facilitate a resolution between you and the provider, which may include compensation or repair depending on the case.' },
            { q: 'Will my home address be visible to the provider before the booking is confirmed?', a: 'Your full address is only shared with the assigned service provider once a booking has been confirmed. This ensures your privacy is protected until a trusted match has been made.' }
        ]
    },
    {
        category: 'For Providers',
        questions: [
            { q: 'How do I register as a service provider on Serva?', a: 'To join Serva as a service provider, visit our website and complete the service provider’s onboarding form. You will be required to provide your personal details, the service(s) you offer, your valid NIN, and your CAC number (if you operate a registered business). Our onboarding team will review your application and contact you within a short period to complete the process.' },
            { q: 'Is there a fee to join Serva as a provider?', a: 'No. Joining Serva as a service provider is completely free. There are no registration fees, listing fees, or monthly charges. Serva only earns when you earn through a small commission on successfully completed and paid services.' },
            { q: 'How does Serva\'s commission work?', a: 'Serva operates a transparent, fixed commission model. For everyday services (e.g., house chores, errands, maintenance), Serva takes a 10% commission on services valued below ₦100,000 and 15% on services valued above ₦100,000. For larger project-based services, the commission is 10% for jobs between ₦100,000 and ₦350,000, and 15% for jobs above ₦350,000. All commission rates are communicated clearly during onboarding, no surprises.' },
            { q: 'How and when do I receive my earnings after a job?', a: 'Once a service is completed your earnings (after Serva\'s commission) are processed and transferred to your registered account.' },
            { q: 'Can I list more than one type of service?', a: 'No. If you are skilled in more than one area, you have to choose ONE of the multiple services to be shown on your profile.' }
        ]
    },
    {
        category: 'Location & Platform',
        questions: [
            { q: 'Where is Serva currently available?', a: 'Serva is currently available in Awka, Anambra State, Nigeria. This is our launch city and we are actively growing our provider network here. We have plans to expand to other cities across Nigeria and beyond in the near future.' },
            { q: 'Do service providers come to my exact location?', a: 'Yes. Serva is a location-based platform, meaning service providers come directly to your home, office, or wherever the service is needed.' },
            { q: 'Do I need to create an account to book a service?', a: 'Yes, creating an account is required to complete a booking on Serva. Registration is quick and free, all you need is your name, phone number, and email address.' },
            { q: 'Is there a mobile app or is it website only for now?', a: 'Serva is currently available as a website, accessible from any smartphone, tablet, or computer browser. Our website is designed to be mobile-friendly for a smooth experience on your phone. A dedicated mobile app is part of our roadmap as we grow.' },
            { q: 'What if I have trouble using the website?', a: 'If you experience any difficulty navigating or using the Serva website, our customer support team is available to assist you. You can reach us via the contact options on the website, including email, or our WhatsApp support line.' },
            { q: 'I am new to Awka, how do I find services near me?', a: 'Welcome to Awka! Serva was built with you in mind. Simply create an account, enter your current address or allow the platform to detect your location, and you will immediately see all available services and providers near you.' },
            { q: 'Can Serva accommodate individuals with physical disabilities or special needs?', a: 'Absolutely. Serva is committed to accessibility and inclusion. When booking, you can include specific notes about any special requirements or accessibility needs, and our team will work to match you with a provider who is equipped to serve you appropriately.' }
        ]
    }
];
